name: palestine_sms_misr
description: Lightweight SMS Misr gateway implementation in dart (unofficial).
version: 0.0.8

homepage: https://github.com/msayed-net/PalestineDevelopers

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.4

dev_dependencies:
  lint: ^1.0.0
  test: ^1.20.1
